# Generated by Buildr 1.4.7, change to your liking


# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "splice-certmaker"
COPYRIGHT = ""

CANDLEPIN = 'candlepin:candlepin-cert:jar:0.7.12'
# this needs to go away!
CANDLEPIN_FULL = 'candlepin:candlepin-full:jar:0.7.12'

BOUNCYCASTLE = group('bcprov-jdk16', :under=>'org.bouncycastle', :version=>'1.46')

LOG4J = 'log4j:log4j:jar:1.2.14'

HIBERNATE = ['org.hibernate:hibernate-core:jar:3.3.2.GA',
             'org.hibernate:hibernate-annotations:jar:3.4.0.GA',
             'org.hibernate:hibernate-commons-annotations:jar:3.3.0.ga',
             'javax.persistence:persistence-api:jar:1.0',
             'org.hibernate:hibernate-entitymanager:jar:3.4.0.GA',
             'org.hibernate:hibernate-tools:jar:3.2.4.GA']


#COMMONS = ['commons-codec:commons-codec:jar:1.4',
#           'commons-collections:commons-collections:jar:3.1',
#           'commons-io:commons-io:jar:1.3.2',
#           'commons-logging:commons-logging:jar:1.1.1',
#           'commons-lang:commons-lang:jar:2.5']
COMMONS = 'commons-lang:commons-lang:jar:2.5'

COLLECTIONS = 'com.google.collections:google-collections:jar:1.0'

JACKSON = [group('jackson-core-lgpl',
                 'jackson-mapper-lgpl',
                 'jackson-jaxrs',
                 'jackson-xc',
                 :under => 'org.codehaus.jackson',
                 :version => '1.9.2')]

JUNIT = ['junit:junit:jar:4.5', 'org.mockito:mockito-all:jar:1.8.5']

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"

desc "The Splice-certmaker project"
define "splice-certmaker" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  compile.with [CANDLEPIN_FULL, BOUNCYCASTLE, COMMONS, COLLECTIONS, JACKSON, LOG4J, HIBERNATE] # Add classpath dependencies
  package(:jar)

  test.with [JUNIT]

end
